### ISSUE TITLE
Question in regards to animation / fbx files

### ISSUE THREAD

**Issue by MostHated** [coryleach/UnityAssetCache#1]
Hey there,
    I came across this today, and while it seems great overall, it made me wonder if it might be useful for me in a different way. It might be easier if I mention what my end goal is. I am trying to load an FBX asset containing animations using AssetDatabase.GetAssetPath, then getting the AnimationClips from it, modifying some of the curves via code and then wanting to export it back to a new FBX. Right now, I go through the process and modify them, which seems to work fine. When you look in the project view and expand the FBX and click on the animation clips and check them in the animation preview in the inspector, they are perfect, but the actual animations in the FBX file are still the original ones. If you hit reimport on the file, the ones you just saw in the project view are gone and replaced by the ones actually in the FBX. 

It seems that when I try to load the file to export it, I think it is loading the asset as it originally was imported, disregarding the modified animation clips that you see in the project view. So I am wondering if perhaps somehow your asset might be able to help me hold a reference to the fbx with the modified animation clips so it can be exported with them instead of the originals in the file? 

Hopefully that makes sense, lol.
Thanks,
-MH

**Comment by coryleach** [comment]
Hey,

Sorry I don't think anything in this repo is going to help you.

Sounds like you're successfully loading the fbx asset and modifying it in memory but when you're writing your changes to disk it's not writing your changes. I don't believe that Unity has the facilities to actually write modifications to the fbx file. Fbx files are generally something Unity only imports and doesn't export. You can of course modify the import settings for an fbx file but those settings are written to the meta or library files rather than the fbx itself. This is the same with many other asset types in Unity. If instead of exporting your modified animations as part of the fbx you exported them as separate native Unity animation file assets you might have more success.

-Cory
